### ISSUE TITLE
Add all committees from list at `relaton-data-iho` repo

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-iho#6]
```
[relaton-iho] WARNING: invalid committee: NSHC
[relaton-iho] WARNING: invalid committee: CHRIS
[relaton-iho] WARNING: invalid committee: CHRIS
```

These are listed in the https://github.com/relaton/relaton-data-iho README file.

**Comment by andrew2net** [comment]
@ronaldtse I thought NSHC is a subcommission of IRCC. Should we allow values form all levels from the list?
As I understand HSSC previously was CHRIS. Shouldn't be CHRIS replaced by HSSC in the data files?

**Comment by ronaldtse** [comment]
@andrew2net this is an issue. I'm not sure what the best way to do so is here, since the HSSC and the IRCC have a different structure.

* HSSC: a committee that contains working groups
* IRCC: a committee that contains committees, commissions, working groups; and the committees and commissions have working groups

If we have the hierarchical structure data encoded anyway, we could help the user look up the "real hierarchy" if it is not specified.

Is something like this reasonable?

```yaml
# full specification
- committee: IRCC
  -  commission: MBSHC
     - working_group: BASWG

# simple specification (will auto expand)
- working_group: BASWG

- committee: IRCC
  - working_group: EC-IHO
    - working_group: IENWG

- committee: IRCC
    committee: DCDB

- committee: IRCC
  - committee: GEBCO
    - committee_2: GGC

```

> As I understand HSSC previously was CHRIS. Shouldn't be CHRIS replaced by HSSC in the data files?

We should still support the old CHRIS because some documents were published then, and haven't been changed since.

**Comment by andrew2net** [comment]
> Is something like this reasonable?
> 
> ```yaml
> # full specification
> - committee: IRCC
>   -  commission: MBSHC
>      - working_group: BASWG
> 
> # simple specification (will auto expand)
> - working_group: BASWG
> 
> - committee: IRCC
>   - working_group: EC-IHO
>     - working_group: IENWG
> 
> - committee: IRCC
>     committee: DCDB
> 
> - committee: IRCC
>   - committee: GEBCO
>     - committee_2: GGC
> ```

@ronaldtse however the YAML isn't correct it could be implemented by ruby classes. The YAML should be:
```yaml
# full specification
editorialgroup:
  committee:
    - name: IRCC
      commission:
        - name: RHCs
          workgroup:
            - name: MBSHC
              workgroup:
                - name: BASWG

editorialgroup:
  committee:
    - name: IRCC
      workgroup:
        - name: EC-IHO
          workgroup:
            - name: IENWG

editorialgroup:
  committee:
    - name: IRCC
      committee:
        - name: DCDB

editorialgroup:
  committee:
    - name: IRCC
      committee:
        - name: GEBCO
          committee:
            - name: GGC
```
do you mean if we specify only a leaf of the structure:
```yaml
# simple specification (will auto expand)
editorialgroup:
  workgroup:
    - name: BASWG
```
it should expand the full branch?
```yaml
# full specification
editorialgroup:
  committee:
    - name: IRCC
      commission:
        - name: RHCs
          workgroup:
            - name: MBSHC
              workgroup:
                - name: BASWG
```

**Comment by ronaldtse** [comment]
@andrew2net yes, there are two things:

1. It is difficult for a normal human to write all of those items, an auto-expand would be very useful.
2. We also want to support the hierarchy look  up as in https://github.com/relaton/relaton-iho/issues/6#issuecomment-653605578

**Comment by andrew2net** [comment]
@ronaldtse ok, I'll implement the hierarchy and auto-expand. But we need to update the [grammar](https://github.com/metanorma/metanorma-model-iso/blob/4b7ae2e5f751df1c435dc29275e6ca93fb3f6276/grammars/iho.rnc#L13). Ping @opoudjis

**Comment by opoudjis** [comment]
Yuck. OK, adding to IHO grammar.

**Comment by ronaldtse** [comment]
Wait @opoudjis what are you adding?

**Comment by opoudjis** [comment]
committee = element committee { IHO_Group }
workgroup = element committee { IHO_Group }
commission = element committee { IHO_Group }

IHO_Group =
  element name { text }?,
  element abbreviation { text },
  (committee | workgroup | commission)*

**Comment by opoudjis** [comment]
This seems to have no impact for output: the working groups are not being output in IHO cover pages.

**Comment by ronaldtse** [comment]
We’re not changing grammar but just allowing a shortcut way of expressing the same structure for expansion. So it shouldn’t affect metanorma.

**Comment by opoudjis** [comment]
We very clearly are changing the grammar, because the same grammar is used by Relaton and by Metanorma, and this is an explicit request to allow nesting of editorial groups within Relaton for IHO.

**Comment by andrew2net** [comment]
@ronaldtse also we need to update relaton-data-iho. For example the [data](https://github.com/relaton/relaton-data-iho/blob/0e83e6af93ae92eaa44556862fb74e4369b70b51/data/b-1.yaml#L10) should be:
```yaml
...
editorialgroup:
  - committee:
      abbreviation: hssc
      name: Hydrographic Services and Standards Committee
  - committee:
      abbreviation: IRCC
      name: Inter-Regional Coordination Committee
      committee:
        abbreviation: GEBCO
        name: JOINT IHO-IOC GUIDING COMMITTEE FOR THE GENERAL BATHYMETRIC CHART OF THE OCEANS
...
```
I can make a script to update all the data if you agree.
